import { createGlobalStyle } from "styled-components";
import NeonThick2 from "../font/NeonThick2.woff2";
import NeonThick from "../font/NeonThick.woff";
import ZCoolXiaoWei from "../font/XiaoWei-Regular.ttf";
import Lobster from "../font/LobsterTwo.ttf";

export const GlobalStyles = createGlobalStyle`
* {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
  font-family: "Encode Sans Expanded", sans-serif;
  
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;

  --container-width-lg: 75%;
  --container-width-md: 86%;
  --container-width-sm: 90%;
}

:root{
  --color-bg: #000;
  --color-bg1: #f9e4c8;
  --transition: all 500ms ease;
  --color-sidebar-link: #fff;
  --color-hover-link: #fbeec1;
}

::-webkit-scrollbar {
  display: none;
}

.top-react-icons {
  color: var(--color-sidebar-link);
}

// @font-face {
//   font-family: 'Font Neon';
//   src: local('Font Neon'), local('FontNeon'),
//   url(${NeonThick2}) format('woff2'),
//   url(${NeonThick}) format('woff');
//   font-weight: 300;
//   font-style: normal;
// }

@font-face {
  font-family: 'Font Neon';
  src: url(${NeonThick});
}

@font-face{
  font-family: 'XiaoWei';
  src: url(${ZCoolXiaoWei});
  font-weight: normal;
  font-style: normal;
}

@font-face{
  font-family: 'Lobster';
  src: url(${Lobster});
  font-weight: normal;
  font-style: normal;
}

.gradient__text{
  background: var(--gradient-text);
  background-clip: text;
  -webkit-background-clop: text;
  -webkit-text-fill-color: transparent;
}

.section__padding {
  padding: 4rem 6rem;
}

.section__margin {
  margin: 4rem 6rem;
}

.scale-up-center {
	-webkit-animation: scale-up-center 0.4s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
	        animation: scale-up-center 0.4s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2022-7-8 12:42:40
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation scale-up-center
 * ----------------------------------------
 */
@-webkit-keyframes scale-up-center {
  0% {
    -webkit-transform: scale(0.5);
            transform: scale(0.5);
  }
  100% {
    -webkit-transform: scale(1);
            transform: scale(1);
  }
}
@keyframes scale-up-center {
  0% {
    -webkit-transform: scale(0.5) rotate(0);
            transform: scale(0.5) rotate(0);
  }
  100% {
    -webkit-transform: scale(1) rotate(720deg);
            transform: scale(1) rotate(720deg);
  }
}

@keyframes fadeIn {
  0% {
    opacity: 0;
  }
  100% {
    opacity: 1;
  }
}

@-moz-keyframes fadeIn {
  0% {
    opacity: 0;
  }
  100% {
    opacity: 1;
  }
}

@-webkit-keyframes fadeIn {
  0% {
    opacity: 0;
  }
  100% {
    opacity: 1;
  }
}

@-o-keyframes fadeIn {
  0% {
    opacity: 0;
  }
  100% {
    opacity: 1;
  }
}

@-ms-keyframes fadeIn {
  0% {
    opacity: 0;
  }
  100% {
    opacity: 1;
  }
}

@keyframes bounceIn {
	0% {
		opacity: 0;
		transform: scale(.3);
	}

	50% {
		transform: scale(1.05);
	}

	70% {
		transform: scale(.9);
	}

	100% {
		opacity: 1;
		transform: scale(1);
	}
}

@keyframes rotation {
  from {
    transform: rotate(0deg);
  }
  to {
    transform: rotate(359deg);
  }
}

@media screen and (max-width: 700px){
  .section__padding{
    padding: 4rem;
  }

  .section__margin{
    padding: 4rem;
  }
}

@media screen and (max-width: 550px){
  .section__padding{
    padding: 4rem 2rem;
  }

  .section__margin{
    padding: 4rem 2rem;
  }
}

////////// SETTING HOME PAGE ///////////////
.wrapper-page{
  width: 100%;
  height: 100%;
  position: absolute;
}

.top-tag {
  bottom: auto;
  top: 96px;
}

.tags {
  color: #ffd700;
  opacity: 0.6;
  position: absolute;
  bottom: 0;
  left: 120px;
  font-size: 18px;
  font-family: "Font Neon";
  cursor: default;
}

.bottom-tag-html{
  margin-left: -20px;
}

.container{
  width: 100%;
  will-change: contents;
  height: 90%;
  min-height: 566px;
  position: absolute;
  opacity: 0;
  top: 5%;
  margin: 0 auto;
  z-index: 1;
  transform-style: preserve-3d;
  animation: fadeIn 1s forwards;
  animation-delay: 1s;
}

.about-page{
  .text-zone{
    position: absolute;
    left: 10%;
    top: 50%;
    transform: translateY(-50%);
    width: 35%;
    vertical-align: middle;
    display: table-cell;
    max-height: 90%;

    h1{
      font-size: 53px;
      font-family: "XiaoWei";
      color: #ffd700;
      font-weight: 400;
      margin-top: 0;
      position: relative;
      margin-bottom: 40px;
      left: 10px;

      &::before{
        content: "<h1>";
        font-family: "Lobster";
        font-size: 18px;
        position: absolute;
        margin-top: -10px;
        left: -10px;
        opacity: 0.6;
        line-height: 18px;
      }

      &::after{
        content: "<h1 />";
        font-family: "Lobster";
        font-size: 18px;
        line-height: 18px;
        position: absolute;
        left: -30px;
        bottom: -20px;
        margin-left: 20px;
        opacity: 0.6;
      }
    }

    p{
      font-style: 13px;
      color: #fff;
      font-family: sans-serif;
      font-weight: 300;
      min-width: fit-content;
      animation: pulse 1s;

      &:nth-of-type(1) {
        animation-delay: 1.1s;
      }

      &:nth-of-type(2) {
        animation-delay: 1.2s;
      }

      &:nth-of-type(3) {
        animation-delay: 1.3s;
      }
    }


  }

  .text-animate-hover{
    &:hover{
      color: #fff;
    }
  }
}
`;

// export const fontFaces = css`
//   @font-face {
//     font-family: "Neon";
//     src: url(${myFontNeon}) format("otf");
//     font-weight: bold;
//     font-style: normal;
//   }
// `;
